CREATE SCHEMA "STORE";
CREATE TABLE "STORE"."ITEMS" ("ID" INTEGER NOT NULL, "NAME" VARCHAR(100), "DESCRIPTION" VARCHAR(2000), "PRICE" DECIMAL(10,2), "SHORTNAME" VARCHAR(20));
ALTER TABLE "STORE"."ITEMS" ADD CONSTRAINT "SQL160219014409770" PRIMARY KEY ("ID");

SET SCHEMA store;
INSERT INTO items VALUES (1,'Pappy Van Winkle Family Reserve 20yr','20 Year, 90.4 Proof This is the #1 rated Bourbon Whiskey in the world—Rated 99 out of 100 by the World Spirits Championship. This bourbon is aged 20 years and bottled at 90.4 proof. This whiskey is wonderfully smooth and rich. No other bourbon today can stand 20 years of aging, but this bourbon does it with style. "Pappy" Van Winkle was a true character. This bourbon, like "Pappy", is full of character that makes it a very special whiskey. It has been put in the class of a fine after dinner cognac. Rated 99 by the Beverage Tasting Institute.',1399.95,'pappy-20yr', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (2,'Blanton''s Original Single Barrel Bourbon Whiskey','The finest bourbon in the world comes from a single barrel. That''s the way Colonel Albert B. Blanton first bottled his private reserve bourbon nearly a century ago. Blanton believed the "center-cut" or middle sections of Warehouse H were the best for aging his  Personally tasting and choosing each barrel, these barrels were reserved and bottled for ambassadors, dignitaries, family and friends becoming the world''s first single barrel  His time honored tradition lives on today as only a handful of barrels from the center of Warehouse H are selected to become Blanton''s Single Barrel ',49.99,'blantons', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (3,'Eagle Rare 10 Year Kentucky Straight Bourbon Whiskey','Eagle Rare Kentucky Straight Bourbon Whiskey is masterfully crafted and carefully aged for no less than ten years. The rareness of this great breed of bourbon is evident in its complex aroma, as well as the smooth and lingering taste. Eagle Rare is a bourbon that lives up to its name with its lofty, distinctive taste experience.',39.99,'eagle-rare-10yr', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (4,'Booker''s Single Barrel Bourbon','Booker''s Bourbon is a rare barrel-strength bourbon, bottled uncut and unfiltered. But you obviously know a good bit about bourbon, because you don''t end up here by mistake. We don''t advertise. We don''t do social media. We just do  We focus on the sweet spot. The center of the rackhouse where the temperature and humidity stars align to create the deepest and most intense flavors. Once it''s aged to perfection, which always varies, the liquid is bottled uncut and unfiltered. We don''t add, we don''t water down, and we don''t apologize for it. For some people, it may be too much. But for true bourbon fans, it''s probably the best ever.',41.99,'bookers', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (5,'Woodford Reserve Double Oaked','An innovative approach to twice-barreled bourbon creates the rich and colorful flavor of Woodford Reserve Double Oaked. Uniquely matured in separate, charred oak barrels – the second barrel deeply toasted before a light charring – extracts additional amounts of soft, sweet oak character.',55.99,'woodford-dbl-oak', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (6,'Four Roses Small Batch','Mingling multiple Bourbon recipes is an art in itself. Four original and limited Bourbon recipes have been expertly selected by our Master Distiller at the peak of maturation to create a perfectly balanced Small Batch Bourbon that rewards you with a mellow symphony of rich, spicy flavors along with sweet, fruity aromas and hints of sweet oak and caramel. Finishes soft, smooth and pleasantly long. Best enjoyed straight up, on the rocks or with a splash. 90 proof. 45% alcohol/volume.',34.99,'four-roses-small', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (7,'Old Forester 1870 Original Batch','Old Forester 1870 Original Batch echoes George Garvin Brown''s original 1870 batching process. Back then, Brown batched barrels obtained from three distilleries to create a consistent flavor profile. To emulate that process today, we also select barrels from three warehouses, each barrel originating from a different day of production, with a different entry proof and a different age profile. The three expressions of Old Forester are then batched together to craft Old Forester 1870 Original Batch. This 90-proof bourbon will be minimally filtered, to honor the processes available to George Garvin Brown at that time.',43.99,'old-forester-1870', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (8,'Baker''s Kentucky Straight Bourbon Whiskey','The mix of grains, yeast, and seven soothing years in new oak combine to give this bourbon a deeply mellow, richly flavorful, medium-bodied taste with a delicious aroma full of fruit and vanilla. Baker''s is best served in a snifter with a splash of spring water.',54.99,'bakers', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (9,'Widow Jane 8yr Straight Bourbon Whiskey','As great whiskey distillers throughout the world — from Kentucky to Scotland — have long known, it takes sweet water from tough rock to make great whiskey. And, that''s what Widow Jane Whiskey is all about. This 8 year whiskey is aged to perfection. It drinks like a 20 year bourbon with its deep cherry notes and light tannic finish.',61.99,'widow-jane-8yr', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (10,'Evan Williams Bourbon 1783','Evan Williams 1783 is our signature, small batch Bourbon meaning that each batch is pulled from no more than 80 hand-selected barrels. It is extra-aged and uses the same sour mash process and traditional recipe made popular by our namesake. The result is a classic Bourbon- smooth rich, and worthy of the name.',14.99,'evan-williams-1783', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (11,'Basil Hayden''s Bourbon Whiskey','In 1796, Master Distiller Basil Hayden Sr. broke the rules by mixing small grains into the mash of a traditional corn base. A Maryland transplant unafraid to stand out amidst the residing establishment, Basil conjectured that the spicy flavor of rye would be a striking complement to the sweet smoothness of corn in his distillery''s standard  And much to the chagrin of the traditionalist set, Basil was right. His recipe was a masterpiece, resulting in a unique, singular small batch bourbon whiskey that was blessed with rich hints of peppermint, notes of pepper, slight citrus overtones, and a spicy, warming finish. Artfully aged at a relatively mild 80 proof, Basil Hayden''s is as novel and delectable a bourbon whiskey as it was when the master distiller rolled out his first barrel over 200 years ago. Marked by a rich cascade of aromas and flavors, Basil Hayden''s is still a small batch bourbon, but with broader appeal.',43.99,'basil-hayden', CURRENT_DATE, 'mrdowden');
INSERT INTO items VALUES (12,'Elijah Craig 12 Year Old Barrel Proof Bourbon','Named after the father of Bourbon Rev. Elijah Craig this limited release Small Batch, twelve-year-old Bourbon is bottled at Barrel Proof and without chill filtering, preserving the natural flavors produced during the aging process. At full Barrel Proof, you can enjoy the Bourbon much the same way our Master Distiller does when he samples straight from the barrel or, if you choose, add water to reduce the proof to your liking.',26.99,'elijah-craig-12yo', CURRENT_DATE, 'mrdowden');
